export const runtimeConfigBehaviorNames: readonly string[] = [
  "reads web, Postgres, and worker settings from environment variables",
  "supports explicit local file storage when database config is absent",
  "rejects ambiguous storage configuration and invalid numeric values",
  "requires an explicit non-production opt-in for legacy mock batches",
  "can require Postgres for production entrypoints",
  "rejects simulation workers when simulation data is disabled",
  "can require any durable store for the production web entrypoint",
  "rejects local live-draft fixtures in production",
  "requires explicit shared storage settings for the default web mode",
  "requires production email verification delivery and an HTTPS public origin",
  "reports production/domain readiness for a Postgres-backed deploy target",
  "blocks production/domain readiness when Postgres env is missing",
  "reports manual commissioner entry as ready without OpenAI configuration",
  "blocks production/domain readiness when private draft storage is not configured",
  "blocks local live-draft fixtures from production/domain readiness",
  "blocks file-backed stores for production/domain readiness",
  "blocks non-Postgres database URLs for production/domain readiness",
  "requires an explicit production bind port",
  "switches the news refresh off for an offline run",
];
