import vm from "node:vm";
import { describe, expect, it } from "vitest";
import { leagueConfig } from "../config/league.js";
import { liveDraftHtml } from "../src/liveDraftUi.js";
import { parseMockDraftScript } from "../src/modeling/mockScript.js";

const buildAroundScriptFromLiveUi = (target: Record<string, unknown>): string => {
  const helperStart = liveDraftHtml.indexOf("    const buildAroundAnchorPriceFor = target => {");
  const helperEnd = liveDraftHtml.indexOf("    const selectTargetForBuildAround = target => {", helperStart);
  expect(helperStart).toBeGreaterThan(-1);
  expect(helperEnd).toBeGreaterThan(helperStart);

  const helperScript = liveDraftHtml.slice(helperStart, helperEnd);
  const context = { target };
  vm.runInNewContext(
    `${helperScript}\nglobalThis.result = buildAroundScriptForTarget(target);`,
    context,
  );
  return String((context as { result?: unknown }).result ?? "");
};

describe("live draft UI shell", () => {
  it("renders the draft-room controls needed for search, add, and roster review", () => {
    expect(liveDraftHtml).toContain("button:hover:not(:disabled)");
    expect(liveDraftHtml).toContain("color: #f4f8fc;");
    expect(liveDraftHtml).toContain("button.primary:hover:not(:disabled)");
    expect(liveDraftHtml).toContain("button.primary:disabled");
    expect(liveDraftHtml).toContain("class=\"board-search-row\"");
    expect(liveDraftHtml).toContain("class=\"search board-search-input\" id=\"board-search\"");
    expect(liveDraftHtml).not.toContain("<nav class=\"sidebar\" aria-label=\"Draft room controls\">\n      <input class=\"search\" id=\"board-search\"");
    expect(liveDraftHtml).toContain("id=\"header-board-search\"");
    expect(liveDraftHtml).toContain("<details class=\"sidebar-section session-tools\">");
    expect(liveDraftHtml).toContain("<summary class=\"session-tools-summary\">");
    expect(liveDraftHtml).toContain("id=\"session-summary-label\"");
    expect(liveDraftHtml).toContain("class=\"session-tools-body\"");
    expect(liveDraftHtml).toContain("id=\"room-title\"");
    expect(liveDraftHtml).toContain("id=\"room-mode-indicator\"");
    expect(liveDraftHtml).toContain("id=\"draft-start-banner\"");
    expect(liveDraftHtml).toContain("id=\"draft-countdown-value\"");
    expect(liveDraftHtml).toContain("id=\"header-quick-sale-form\"");
    expect(liveDraftHtml).toContain("id=\"header-quick-sale-command\"");
    expect(liveDraftHtml).toContain("id=\"header-draft-actions\"");
    expect(liveDraftHtml).toContain("id=\"header-export-json-button\"");
    expect(liveDraftHtml).toContain("id=\"header-export-csv-button\"");
    expect(liveDraftHtml).toContain("id=\"header-export-bundle-button\"");
    expect(liveDraftHtml).toContain("id=\"header-import-log-button\"");
    expect(liveDraftHtml).toContain("id=\"header-undo-button\"");
    expect(liveDraftHtml).toContain("id=\"header-reset-button\"");
    expect(liveDraftHtml).toContain("id=\"end-draft-button\"");
    expect(liveDraftHtml).toContain("id=\"quick-sale-command\"");
    expect(liveDraftHtml).toContain("id=\"board\"");
    expect(liveDraftHtml).toContain("id=\"board-cards\"");
    expect(liveDraftHtml).not.toContain("id=\"position-filters\"");
    expect(liveDraftHtml).toContain("pill.dataset.positionFilter = position;");
    expect(liveDraftHtml).toContain("byId('position-market').addEventListener('click'");
    expect(liveDraftHtml).toContain("id=\"my-needs-filter\"");
    expect(liveDraftHtml).toContain("id=\"team-filter\"");
    expect(liveDraftHtml).toContain("id=\"bye-filter\"");
    expect(liveDraftHtml).toContain("id=\"sort-select\"");
    expect(liveDraftHtml).toContain("id=\"strategy-select\"");
    expect(liveDraftHtml).toContain("id=\"export-json-button\"");
    expect(liveDraftHtml).toContain("id=\"export-csv-button\"");
    expect(liveDraftHtml).toContain("id=\"export-bundle-button\"");
    expect(liveDraftHtml).toContain("id=\"import-log-button\"");
    expect(liveDraftHtml).toContain("id=\"import-log-file\"");
    expect(liveDraftHtml).toContain("id=\"import-conflict-review\"");
    expect(liveDraftHtml).toContain("id=\"draft-session-select\"");
    expect(liveDraftHtml).toContain("id=\"scratch-session-name\"");
    expect(liveDraftHtml).toContain("id=\"open-scratch-session-button\"");
    expect(liveDraftHtml).toContain("id=\"active-session-label\"");
    expect(liveDraftHtml).toContain("id=\"draft-lock-status\"");
    expect(liveDraftHtml).toContain("byId('back-to-draft-room-button').addEventListener('click', () => window.location.assign('/draft-room'));");
    expect(liveDraftHtml).toContain("byId('my-expert-back-button').addEventListener('click', () => window.location.assign('/draft-room'));");
    expect(liveDraftHtml).toContain("byId('player-news-back-button').addEventListener('click', () => window.location.assign('/draft-room'));");
    expect(liveDraftHtml).not.toContain("window.location.assign('/')");
    expect(liveDraftHtml).toContain("<header class=\"draft-header app-page-header\">");
    expect(liveDraftHtml).toContain("id=\"draft-header-menu-slot\"");
    expect(liveDraftHtml).toContain("id=\"app-menu-button\"");
    expect(liveDraftHtml).toContain("id=\"app-menu-list\"");
    expect(liveDraftHtml).toContain("aria-haspopup=\"menu\"");
    expect(liveDraftHtml).toContain("role=\"menu\"");
    expect(liveDraftHtml).toContain("role=\"menuitem\"");
    expect(liveDraftHtml).toContain("aria-current=\"page\"");
    expect(liveDraftHtml).toContain("data-menu-key=\"real-draft\"");
    expect(liveDraftHtml).toContain("data-menu-key=\"mock-draft\"");
    expect(liveDraftHtml).toContain("data-menu-key=\"my-expert\"");
    expect(liveDraftHtml).toContain("data-menu-key=\"player-news\"");
    expect(liveDraftHtml).toContain("data-menu-key=\"mock-results\"");
    expect(liveDraftHtml).not.toContain("role=\"menuitemradio\"");
    expect(liveDraftHtml).not.toContain("<div class=\"window-controls\"");
    expect(liveDraftHtml).toContain("id=\"start-real-draft-button\"");
    expect(liveDraftHtml).toContain("id=\"start-mock-draft-button\"");
    expect(liveDraftHtml).toContain("id=\"draft-mode-real-button\"");
    expect(liveDraftHtml).toContain("id=\"draft-mode-mock-button\"");
    expect(liveDraftHtml).toContain("class=\"draft-mode-choice\"");
    expect(liveDraftHtml).toContain("id=\"mock-batch-runs\"");
    expect(liveDraftHtml).toContain("id=\"run-mock-batch-button\"");
    expect(liveDraftHtml).toContain("id=\"mock-batch-script\"");
    expect(liveDraftHtml).toContain("id=\"see-mock-results-button\"");
    expect(liveDraftHtml).toContain("id=\"draft-mode-status\"");
    expect(liveDraftHtml).toContain("id=\"confirm-start-draft-button\"");
    expect(liveDraftHtml).toContain("id=\"draft-countdown\"");
    expect(liveDraftHtml).toContain("id=\"mock-batch-results\"");
    expect(liveDraftHtml).toContain("id=\"draft-room-view\"");
    expect(liveDraftHtml).toContain("id=\"mock-results-view\"");
    expect(liveDraftHtml).toContain("id=\"mock-results-run-list\"");
    expect(liveDraftHtml).toContain("id=\"mock-results-run-new-button\"");
    expect(liveDraftHtml).toContain("id=\"mock-results-grid\"");
    expect(liveDraftHtml).toContain("id=\"mock-results-title\"");
    expect(liveDraftHtml).toContain("id=\"my-expert-button\"");
    expect(liveDraftHtml).toContain("id=\"my-expert-view\"");
    expect(liveDraftHtml).toContain("id=\"my-expert-recommendations\"");
    expect(liveDraftHtml).toContain("id=\"my-expert-lineup\"");
    expect(liveDraftHtml).toContain("id=\"my-expert-roster\"");
    expect(liveDraftHtml).toContain("id=\"my-expert-integrations\"");
    expect(liveDraftHtml).toContain("id=\"my-expert-connect-panel\"");
    expect(liveDraftHtml).toContain("id=\"my-expert-context-row\"");
    expect(liveDraftHtml).not.toContain("my-expert-header-meta");
    expect(liveDraftHtml).toContain("input.id = 'my-expert-sleeper-identifier'");
    expect(liveDraftHtml).toContain("action.id = 'my-expert-sleeper-connect-button'");
    expect(liveDraftHtml).toContain("my-expert-provider-action");
    expect(liveDraftHtml).toContain("my-expert-provider-feedback");
    expect(liveDraftHtml).toContain("data-sync-provider-key");
    expect(liveDraftHtml).toContain("id=\"my-expert-refresh-button\"");
    expect(liveDraftHtml).toContain("id=\"player-news-button\"");
    expect(liveDraftHtml).toContain("id=\"player-news-view\"");
    expect(liveDraftHtml).toContain("id=\"player-news-feed\"");
    expect(liveDraftHtml).toContain("id=\"player-news-search\"");
    expect(liveDraftHtml).toContain("id=\"player-news-category-filter\"");
    expect(liveDraftHtml).toContain("id=\"player-news-action-filter\"");
    expect(liveDraftHtml).toContain("id=\"player-news-status\"");
    expect(liveDraftHtml).toContain("class=\"player-news-filter-button\"");
    expect(liveDraftHtml).toContain("aria-label=\"News source: All sources\"");
    expect(liveDraftHtml).toContain("aria-label=\"News category: All categories\"");
    expect(liveDraftHtml).toContain("aria-label=\"Draft action: All actions\"");
    expect(liveDraftHtml).toContain("class=\"player-news-filter-options\"");
    expect(liveDraftHtml).toContain("role=\"listbox\"");
    expect(liveDraftHtml).toContain("role=\"option\"");
    expect(liveDraftHtml).not.toContain("<select id=\"player-news-source-filter\"");
    expect(liveDraftHtml).not.toContain("<select id=\"player-news-category-filter\"");
    expect(liveDraftHtml).not.toContain("<select id=\"player-news-action-filter\"");
    expect(liveDraftHtml).toContain("id=\"back-to-draft-room-button\"");
    expect(liveDraftHtml).toContain("id=\"add-owner\"");
    expect(liveDraftHtml).toContain("id=\"add-price\"");
    expect(liveDraftHtml).toContain("id=\"add-submit\"");
    expect(liveDraftHtml).toContain("id=\"sale-warning\"");
    expect(liveDraftHtml).toContain("id=\"roster-owner\"");
    expect(liveDraftHtml).toContain("id=\"roster-slots\"");
    expect(liveDraftHtml).toContain("id=\"side-panel-tabs\"");
    expect(liveDraftHtml).toContain("data-side-panel=\"lineup\"");
    expect(liveDraftHtml).toContain("data-side-panel=\"shortlist\"");
    expect(liveDraftHtml).toContain("data-side-panel=\"draft-path\"");
    expect(liveDraftHtml).toContain("id=\"lineup-panel\"");
    expect(liveDraftHtml).toContain("id=\"shortlist-panel\"");
    expect(liveDraftHtml).toContain("id=\"draft-path-panel\"");
    expect(liveDraftHtml).toContain("id=\"manual-shortlist\"");
    expect(liveDraftHtml).toContain("id=\"model-shortlist\"");
    expect(liveDraftHtml).not.toContain("id=\"owner-needs\"");
    expect(liveDraftHtml).not.toContain("class=\"owner-needs\"");
    expect(liveDraftHtml).not.toContain("className = 'need-chip'");
    expect(liveDraftHtml).toContain("id=\"position-market\"");
    expect(liveDraftHtml).toContain("id=\"readiness-checks\"");
    expect(liveDraftHtml).toContain("id=\"post-draft-audit\"");
    expect(liveDraftHtml).toContain("id=\"draft-path\"");
    expect(liveDraftHtml).toContain("id=\"shortlist\"");
    expect(liveDraftHtml).toContain("id=\"position-context\"");
    expect(liveDraftHtml).toContain("id=\"mock-draft-panel\"");
    expect(liveDraftHtml).toContain("id=\"mock-active-nomination\"");
    expect(liveDraftHtml).toContain("id=\"mock-auction-feed\"");
    expect(liveDraftHtml).toContain("class=\"mock-actions mock-auction-actions\"");
    expect(liveDraftHtml).toContain("id=\"mock-advance-button\"");
    expect(liveDraftHtml).toContain("id=\"mock-nominate-button\"");
    expect(liveDraftHtml).toContain("id=\"mock-cam-win-button\"");
    expect(liveDraftHtml).toContain("id=\"mock-pass-button\"");
    expect(liveDraftHtml).toContain("id=\"mock-next-decision-button\"");
    expect(liveDraftHtml).toContain("id=\"mock-next-round-button\"");
    expect(liveDraftHtml).toContain("id=\"mock-complete-button\"");
    expect(liveDraftHtml).toContain("class=\"sidebar\"");
    expect(liveDraftHtml).toContain("class=\"workspace\"");
    expect(liveDraftHtml).toContain("class=\"sidebar-section\"");
    expect(liveDraftHtml).toContain(".app.draft-active {\n      grid-template-columns: minmax(0, 1fr);\n      grid-template-rows: auto minmax(0, 1fr);");
    expect(liveDraftHtml).toContain(".app.draft-active {\n        grid-template-rows: auto minmax(0, 1fr);\n        height: 100vh;\n        min-height: 100vh;\n        overflow: hidden;");
    expect(liveDraftHtml).toContain(".app.draft-active .workspace {\n        grid-row: 2;\n        height: 100%;\n        min-height: 0;\n        overflow: hidden;");
    expect(liveDraftHtml).toContain(".app.draft-active .header-actions");
    expect(liveDraftHtml).toContain(".app.draft-active .draft-header {\n      grid-template-columns: 48px minmax(0, 1fr) auto;\n      grid-template-rows: auto auto;");
    expect(liveDraftHtml).toContain(".app.draft-active .header-actions {\n      grid-column: 1 / -1;\n      grid-row: 2;");
    expect(liveDraftHtml).toContain(".app.draft-active .header-end-action {\n      grid-column: 3;");
    expect(liveDraftHtml).toContain("class=\"danger header-end-action\"");
    expect(liveDraftHtml).toContain("grid-template-columns: minmax(0, 1fr) clamp(340px, 24vw, 410px)");
    expect(liveDraftHtml).toContain("let boardSortKey = 'liveExpectedPrice';");
    expect(liveDraftHtml).toContain("<option value=\"liveExpectedPrice\">Market price</option>");
    expect(liveDraftHtml).toContain("<option value=\"seasonProjection\">Season points</option>");
    expect(liveDraftHtml).toContain("const boardSortKeys = Object.keys(sortLabels);");
    expect(liveDraftHtml).toContain("liveExpectedPrice: 'Market'");
    expect(liveDraftHtml).toContain("return (rightValue - leftValue) || defaultTieBreak;");
    expect(liveDraftHtml).toContain("<th style=\"width:350px\">Player</th>");
    expect(liveDraftHtml).toContain("<th style=\"width:52px\">Pos</th>");
    expect(liveDraftHtml).toContain("<th class=\"money\" style=\"width:78px\">Season</th>");
    expect(liveDraftHtml).toContain("<th class=\"money\" style=\"width:76px\">Market</th>");
    expect(liveDraftHtml).not.toContain("<th class=\"money\" style=\"width:66px\">Exp</th>");
    expect(liveDraftHtml).not.toContain("<th class=\"money\" style=\"width:66px\">Live</th>");
    expect(liveDraftHtml).toContain("marketPriceCell(row, target)");
    expect(liveDraftHtml).toContain("const addCell = tableCell(row, '', 'center add-cell');");
    expect(liveDraftHtml).toContain(".board-table tbody td.add-cell");
    expect(liveDraftHtml).toContain("vertical-align: top;");
    expect(liveDraftHtml).toContain("stack.className = 'market-price-stack';");
    expect(liveDraftHtml).toContain(".market-price-stack {");
    expect(liveDraftHtml).not.toContain(".market-price-cell {\n      display: grid;");
    expect(liveDraftHtml).not.toContain("class=\"sort-heading\"");
    expect(liveDraftHtml).not.toContain("[data-sort-key]");
    expect(liveDraftHtml).not.toContain("button.dataset.activeSort");
    expect(liveDraftHtml).not.toContain("aria-pressed', String(isActive)");
    expect(liveDraftHtml).not.toContain(".sort-heading:hover");
    expect(liveDraftHtml).not.toContain("let boardSortDirection");
    expect(liveDraftHtml).not.toContain("boardSortDirection = boardSortDirection === 'asc' ? 'desc' : 'asc'");
    expect(liveDraftHtml).not.toContain("' ^'");
    expect(liveDraftHtml).not.toContain("' v'");
    expect(liveDraftHtml).not.toContain(".split(':')");
    expect(liveDraftHtml).not.toContain("Draft priority");
    expect(liveDraftHtml).not.toContain("<th class=\"money\" style=\"width:86px\">Priority</th>");
    expect(liveDraftHtml).not.toContain("id=\"hide-deep-filter\"");
    expect(liveDraftHtml).not.toContain("Hide $1/fallback");
    expect(liveDraftHtml).not.toContain("data-sort-key=\"valueScore\">Priority");
  });

  it("includes board behavior for position filters, sortable values, and draft-day guardrails", () => {
    expect(liveDraftHtml).toContain("const boardPositions = ['ALL', 'RB', 'WR', 'TE', 'QB', 'FLEX', 'K', 'DST']");
    expect(liveDraftHtml).toContain("boardPositionFilter = boardPositionFilter === nextPosition ? 'ALL' : nextPosition;");
    expect(liveDraftHtml).toContain("const setBoardPositionFilter = nextPosition => {");
    expect(liveDraftHtml).not.toContain("dataset.needPositionFilter");
    expect(liveDraftHtml).not.toContain("byId('owner-needs').addEventListener('click'");
    expect(liveDraftHtml).not.toContain("data-need-position-filter");
    expect(liveDraftHtml).toContain("const valueGapFor = target => target.personalValue - target.liveExpectedPrice");
    expect(liveDraftHtml).toContain("[selectedBidLabelFor(target), money(bidPrice), '']");
    expect(liveDraftHtml).toContain("['Season', scoreText(target.seasonProjection), '']");
    expect(liveDraftHtml).toContain("const selectedMockAuctionPriceFor = target =>");
    expect(liveDraftHtml).toContain("const selectedBidLabelFor = target =>");
    expect(liveDraftHtml).toContain("selectedBidLabelFor(target)");
    expect(liveDraftHtml).toContain("selectedBidPriceFor(target)");
    expect(liveDraftHtml).toContain("return 'Current';");
    expect(liveDraftHtml).toContain("return isActiveDraft() && currentDraftMode === 'interactive-mock' ? 'Path max' : 'Bid';");
    expect(liveDraftHtml).not.toContain("priorityAtPriceFor");
    expect(liveDraftHtml).toContain("const strategyValueLabels =");
    expect(liveDraftHtml).toContain("const renderStrategyValues = target =>");
    expect(liveDraftHtml).toContain("target.strategyValues");
    expect(liveDraftHtml).toContain("scoreText(target.week1Projection)");
    expect(liveDraftHtml).toContain("scoreText(target.seasonProjection)");
    expect(liveDraftHtml).toContain("const tierDropsFor = targets =>");
    expect(liveDraftHtml).toContain("'next ' + target.position + ' -' + money(tierDrop)");
    expect(liveDraftHtml).toContain("const saleWarningsFor = (target, owner, price) =>");
    expect(liveDraftHtml).toContain(`const rosterMaximums = ${JSON.stringify(leagueConfig.rosterMaximums)};`);
    expect(liveDraftHtml).toContain("role=\"alert\"");
    expect(liveDraftHtml).toContain("' cannot buy ' + target.name + ': roster limit is '");
    expect(liveDraftHtml).toContain("const alertCommandErrors = data =>");
    expect(liveDraftHtml).toContain("window.alert(messages.join('\\n'))");
    expect(liveDraftHtml).toContain("const renderMutationState = data =>");
    expect(liveDraftHtml).toContain("if (data && data.availableTargets && data.owners) render(data);");
    expect(liveDraftHtml).toContain("renderMutationState(data);");
    expect(liveDraftHtml).toContain("const renderMockDraft = mockDraft =>");
    expect(liveDraftHtml).toContain("mockDraftItem(phase === 'complete' ? 'Mock complete' : 'Mock blocked'");
    expect(liveDraftHtml).toContain("' loaded' + (keeperCount ? ' / ' + keeperCount + ' kept' : '')");
    expect(liveDraftHtml).toContain("const renderDraftMode = state =>");
    expect(liveDraftHtml).toContain("const renderDraftModeChoice = () =>");
    expect(liveDraftHtml).toContain("const renderDraftLifecycle = state =>");
    expect(liveDraftHtml).toContain("const renderRoomModeIndicator = state =>");
    expect(liveDraftHtml).toContain("byId('draft-room-view').classList.toggle('draft-active', isActiveDraft());");
    expect(liveDraftHtml).toContain("const canStartDraft = draftLifecycle === 'setup' || draftLifecycle === 'ready';");
    expect(liveDraftHtml).toContain("byId('confirm-start-draft-button').hidden = !canStartDraft;");
    expect(liveDraftHtml).toContain("byId('header-quick-sale-form').hidden = !(isActiveDraft() && currentDraftMode === 'real');");
    expect(liveDraftHtml).toContain("byId('header-draft-actions').hidden = !isActiveDraft();");
    expect(liveDraftHtml).toContain("byId('header-import-log-button').hidden = !(isActiveDraft() && currentDraftMode === 'real');");
    expect(liveDraftHtml).toContain("byId('mock-draft-panel').hidden = !(isActiveDraft() && currentDraftMode === 'interactive-mock');");
    expect(liveDraftHtml).toContain("const beginDraftCountdown = () =>");
    expect(liveDraftHtml).toContain("const activateDraft = async () =>");
    expect(liveDraftHtml).toContain("const endActiveDraft = async () =>");
    expect(liveDraftHtml).toContain("let draftLifecycle = 'setup'");
    expect(liveDraftHtml).toContain("const draftCountdownSeconds = 5");
    expect(liveDraftHtml).toContain("const setDraftMode = async (mode, options = {}) =>");
    expect(liveDraftHtml).toContain("const practiceSessionForStrategy = strategyKey =>");
    expect(liveDraftHtml).toContain("if (nextMode === 'real') currentDraftSession = 'live';");
    expect(liveDraftHtml).toContain("currentDraftSession = practiceSessionForStrategy(currentStrategyKey);");
    expect(liveDraftHtml).toContain("const draftRoomRouteUrl = mode =>");
    expect(liveDraftHtml).toContain("const draftSessionForMode = mode =>");
    expect(liveDraftHtml).toContain("const hydrateDraftRoomFromLocation = () =>");
    expect(liveDraftHtml).toContain("const draftLifecycleContext = () =>");
    expect(liveDraftHtml).toContain("const sameDraftLifecycleContext = context =>");
    expect(liveDraftHtml).toContain("const previousContext = draftLifecycleContext();");
    expect(liveDraftHtml).toContain("if (!sameDraftLifecycleContext(previousContext) && !isStartingDraft())");
    expect(liveDraftHtml).toContain("draftLifecycle = 'setup';");
    expect(liveDraftHtml).toContain("const openDraftRoomMode = async mode =>");
    expect(liveDraftHtml).toContain("window.location.assign(draftRoomRouteUrl(mode))");
    expect(liveDraftHtml).toContain("window.history.replaceState(null, '', draftRoomRouteUrl(currentDraftMode))");
    expect(liveDraftHtml).toContain("const setActiveRouteShell = route =>");
    expect(liveDraftHtml).toContain("body data-active-route=\"draft-room\"");
    expect(liveDraftHtml).toContain("const setAppMenuOpen = isOpen =>");
    expect(liveDraftHtml).toContain("const setAppMenuCurrent = (key, label) =>");
    expect(liveDraftHtml).toContain("const closeAppMenu = () => setAppMenuOpen(false)");
    expect(liveDraftHtml).toContain("const runMockBatch = async () =>");
    expect(liveDraftHtml).toContain("const mockBatchSeedPrefix = () =>");
    expect(liveDraftHtml).toContain("const mockBatchScript = () =>");
    expect(liveDraftHtml).toContain("Date.now().toString(36)");
    expect(liveDraftHtml).not.toContain("if (!forceNew && latestMockBatchJob");
    expect(liveDraftHtml).toContain("const pollMockBatchJob = async jobId =>");
    expect(liveDraftHtml).toContain("const renderMockBatchButtonState = job =>");
    expect(liveDraftHtml).toContain("const syncMockResultsMenuItem = (job, forceVisible = false) =>");
    expect(liveDraftHtml).toContain("const rosterSlotLabelFor = slot => cleanText(slot).startsWith('BENCH') ? 'BENCH' : slot;");
    expect(liveDraftHtml).toContain("tableCell(row, rosterSlotLabelFor(slot.slot), 'slot');");
    expect(liveDraftHtml).toContain("const currentInteractiveMockResultsReady = () =>");
    expect(liveDraftHtml).toContain("const publishCurrentMockResults = async () =>");
    expect(liveDraftHtml).toContain("'/api/mock/session-results'");
    expect(liveDraftHtml).toContain("expectedCommandCount: currentCommandCount()");
    expect(liveDraftHtml).toContain("job.draftSessionKey === currentDraftSession");
    expect(liveDraftHtml).toContain("Number(job.commandCount || 0) === currentCommandCount()");
    expect(liveDraftHtml).toContain("const syncLatestMockBatchJob = async (forceVisible = false) =>");
    expect(liveDraftHtml).toContain("await syncLatestMockBatchJob()");
    expect(liveDraftHtml).toContain("button.classList.toggle('mock-batch-ready', isReady)");
    expect(liveDraftHtml).toContain("button.textContent = 'See results'");
    expect(liveDraftHtml).toContain("const mockBatchJobMatchesCurrentControls = job =>");
    expect(liveDraftHtml).toContain("jobScript === currentScript");
    expect(liveDraftHtml).toContain("Number(job.runsPerScenario || 25) === currentMockBatchRuns()");
    expect(liveDraftHtml).toContain("mockBatchJobMatchesCurrentControls(latestMockBatchJob)");
    expect(liveDraftHtml).toContain("byId('mock-batch-runs').addEventListener('input', () => {");
    expect(liveDraftHtml).toContain("byId('mock-batch-script').addEventListener('input', () => {");
    expect(liveDraftHtml).toContain("renderMockBatchResultsForJob(latestMockBatchJob)");
    expect(liveDraftHtml).toContain("const renderMockBatchResultsForJob = job =>");
    expect(liveDraftHtml).toContain("'Previous results'");
    expect(liveDraftHtml).toContain("'Run mocks to apply the current strategy, run count, and script.'");
    expect(liveDraftHtml).toContain("renderMockBatchButtonState(latestMockBatchJob);");
    expect(liveDraftHtml).toContain("const renderMockResultsRoute = report =>");
    expect(liveDraftHtml).toContain("const renderMyExpertPage = async () =>");
    expect(liveDraftHtml).toContain("const myExpertUrl = () =>");
    expect(liveDraftHtml).toContain("const myExpertRouteUrl = () => '/my-expert?' + myExpertQueryString()");
    expect(liveDraftHtml).toContain("const renderMyExpertRoute = report =>");
    expect(liveDraftHtml).toContain("const submitMyExpertSleeperConnect = async");
    expect(liveDraftHtml).toContain("const handleMyExpertProviderAction = async");
    expect(liveDraftHtml).toContain("/api/sync/sleeper/preview?");
    expect(liveDraftHtml).toContain("const renderMyExpertLineup = report =>");
    expect(liveDraftHtml).toContain("const myExpertReadOnlyLabel = report =>");
    expect(liveDraftHtml).toContain("const renderPlayerNewsPage = async () =>");
    expect(liveDraftHtml).toContain("const renderPlayerNewsRoute = feed =>");
    expect(liveDraftHtml).toContain("let playerNewsSource = 'all';");
    expect(liveDraftHtml).toContain("const playerNewsUrl = () =>");
    expect(liveDraftHtml).toContain("const playerNewsQueryString = () =>");
    expect(liveDraftHtml).toContain("const playerNewsRouteUrl = () => '/player-news?' + playerNewsQueryString()");
    expect(liveDraftHtml).toContain("const playerNewsPollIntervalMs = () =>");
    expect(liveDraftHtml).toContain("currentDraftMode === 'real' ? 5 * 60 * 1000 : 10 * 60 * 1000");
    expect(liveDraftHtml).toContain("const schedulePlayerNewsPolling = () =>");
    expect(liveDraftHtml).toContain("void refreshPlayerNewsIfCurrentRoute({ background: true })");
    expect(liveDraftHtml).toContain("const stopPlayerNewsPolling = () =>");
    expect(liveDraftHtml).toContain("document.visibilityState === 'hidden'");
    expect(liveDraftHtml).toContain("document.addEventListener('visibilitychange', () =>");
    expect(liveDraftHtml).toContain("const playerNewsUpdatedLabel = feed =>");
    expect(liveDraftHtml).toContain("Refreshing...");
    expect(liveDraftHtml).toContain("const hydratePlayerNewsFromLocation = () =>");
    expect(liveDraftHtml).toContain("playerNewsSource = playerNewsFilterValue('source', params.get('source'), 'all')");
    expect(liveDraftHtml).toContain("const playerNewsFilterLabels =");
    expect(liveDraftHtml).toContain("const playerNewsFilterControlLabels =");
    expect(liveDraftHtml).toContain("const playerNewsFilterValue = (key, value, fallback) =>");
    expect(liveDraftHtml).toContain("const syncPlayerNewsFilterControl = (key, value) =>");
    expect(liveDraftHtml).toContain("const closePlayerNewsFilters = () =>");
    expect(liveDraftHtml).toContain("const focusPlayerNewsFilterOption = (key, value, direction = 0) =>");
    expect(liveDraftHtml).toContain("const handlePlayerNewsFilterButtonKeydown = event =>");
    expect(liveDraftHtml).toContain("const handlePlayerNewsFilterOptionKeydown = event =>");
    expect(liveDraftHtml).toContain("button.setAttribute('aria-label', playerNewsFilterControlLabels[key] + ': ' + optionLabel)");
    expect(liveDraftHtml).toContain("button.addEventListener('keydown', handlePlayerNewsFilterButtonKeydown)");
    expect(liveDraftHtml).toContain("option.addEventListener('keydown', handlePlayerNewsFilterOptionKeydown)");
    expect(liveDraftHtml).toContain("const safePlayerNewsSourceUrl = value =>");
    expect(liveDraftHtml).toContain("const playerNewsDateLabel = item =>");
    expect(liveDraftHtml).toContain("Written ' + playerNewsDateText(item.sourceDate)");
    expect(liveDraftHtml).toContain("return 'No source date';");
    expect(liveDraftHtml).not.toContain("Loaded ' + playerNewsDateText");
    expect(liveDraftHtml).toContain("textElement('span', playerNewsDateLabel(item), 'player-news-date')");
    expect(liveDraftHtml).toContain("playerNewsChip(playerNewsDateLabel(item), 'player-news-date-chip')");
    expect(liveDraftHtml).toContain("link.href = safeUrl");
    expect(liveDraftHtml).toContain("const renderMockResultsGrid = run =>");
    expect(liveDraftHtml).toContain("const renderMockResultsRankingsCard = rankings =>");
    expect(liveDraftHtml).toContain("const mockResultsRankingLabels = () =>");
    expect(liveDraftHtml).toContain("const mockResultsIntelligencePanel = run =>");
    expect(liveDraftHtml).toContain("const mockResultsAnalyticsPanel = report =>");
    expect(liveDraftHtml).toContain("report.analytics.strategyLeaderboard");
    expect(liveDraftHtml).toContain("report.analytics.camScoreRange");
    expect(liveDraftHtml).toContain("report.analytics.topCamRosterPaths");
    expect(liveDraftHtml).toContain("run.camOutcome");
    expect(liveDraftHtml).toContain("team.rankExplanation");
    expect(liveDraftHtml).toContain("ranking.explanation");
    expect(liveDraftHtml).toContain("Math.max(...rankings.map(ranking => ranking.week1Score))");
    expect(liveDraftHtml).toContain("const mockResultsSeasonParts = team =>");
    expect(liveDraftHtml).toContain("team.starterSeasonScore");
    expect(liveDraftHtml).toContain("team.depthScore");
    expect(liveDraftHtml).toContain("team.consistencyScore");
    expect(liveDraftHtml).toContain("run.bestBuild");
    expect(liveDraftHtml).toContain("run.worstBuild");
    expect(liveDraftHtml).toContain("window.location.assign('/mock-results')");
    expect(liveDraftHtml).toContain("const syncMockNominationSelection = mockDraft =>");
    expect(liveDraftHtml).toContain("const canNominateTarget = target =>");
    expect(liveDraftHtml).toContain("className = 'target-action'");
    expect(liveDraftHtml).toContain("className = 'target-action-menu'");
    expect(liveDraftHtml).toContain("target-action-row-open");
    expect(liveDraftHtml).toContain(".board-table tbody tr.target-action-row-open");
    expect(liveDraftHtml).toContain("Add to shortlist");
    expect(liveDraftHtml).toContain("Nominate");
    expect(liveDraftHtml).toContain("if (!isActiveDraft()) menuActions.push(buildAroundAction);");
    expect(liveDraftHtml).toContain("const buildAroundScriptForTarget = target =>");
    expect(liveDraftHtml).toContain("byId('mock-batch-script').value = buildAroundScriptForTarget(target)");
    expect(liveDraftHtml).toContain("byId('run-mock-batch-button').focus()");
    expect(liveDraftHtml).toContain("const selectTargetForNomination = target =>");
    expect(liveDraftHtml).toContain("selectTargetForNomination(target)");
    expect(liveDraftHtml).toContain("id=\"mock-nomination-price\"");
    expect(liveDraftHtml).toContain("let pendingCamNominationPrice = 1");
    expect(liveDraftHtml).toContain("const nominationPriceValue = () =>");
    expect(liveDraftHtml).toContain("const focusNominationPriceInput = () =>");
    expect(liveDraftHtml).toContain("const mockNominationIdeaEvents = mockDraft =>");
    expect(liveDraftHtml).toContain("mockDraft.phase === 'human-nomination' || Boolean(mockDraft.auction)");
    expect(liveDraftHtml).toContain("textElement('strong', 'Cam is nominating')");
    expect(liveDraftHtml).toContain("target ? 'Ready to nominate ' + target.name + ' at ' + money(nominationPriceValue()) : 'Select a player from the board'");
    expect(liveDraftHtml).toContain("renderMockAuctionFeedEvents(mockNominationIdeaEvents(mockDraft))");
    expect(liveDraftHtml).toContain("if (currentState) renderBoard(currentState);\n        renderSaleControls(currentState);\n        return;");
    expect(liveDraftHtml).toContain("const nominationPrice = mockDraft.camDecision ? mockDraft.camDecision.recommendedBid : target.recommendedMaxBid");
    expect(liveDraftHtml).toContain("byId('add-price').value = String(nominationPrice)");
    expect(liveDraftHtml).toContain("const advanceMockDraft = async (action, nominatedPlayerName = selectedTargetName, nominatedPrice = nominationPriceValue()) =>");
    expect(liveDraftHtml).toContain("let pendingCamNominationName = null");
    expect(liveDraftHtml).toContain("const nominationTargetForMockControls = () =>");
    expect(liveDraftHtml).toContain("const nominationTarget = nominationTargetForMockControls();");
    expect(liveDraftHtml).toContain("const canNominate = isMockMode && phase === 'human-nomination' && Boolean(nominationTarget);");
    expect(liveDraftHtml).toContain("let mockAdvanceRequestInFlight = false");
    expect(liveDraftHtml).toContain("let mockAdvanceRequestAction = null");
    expect(liveDraftHtml).toContain("const mockAdvanceBusy = mockAdvanceRequestInFlight;");
    expect(liveDraftHtml).toContain("if (mockAdvanceRequestInFlight) return null;");
    expect(liveDraftHtml).toContain("mockAdvanceRequestInFlight = true;");
    expect(liveDraftHtml).toContain("mockAdvanceRequestAction = action;");
    expect(liveDraftHtml).toContain("mockAdvanceRequestInFlight = false;");
    expect(liveDraftHtml).toContain("mockAdvanceRequestAction = null;");
    expect(liveDraftHtml).toContain("action === 'cam-nominate'");
    expect(liveDraftHtml).toContain("nominatedPlayer: pendingCamNominationName");
    expect(liveDraftHtml).toContain("nominatedPrice: pendingCamNominationPrice");
    expect(liveDraftHtml).toContain("nominateButton.textContent = nominationTarget ? 'Nominate ' + shortPlayerName(nominationTarget.name) : 'Choose nominee';");
    expect(liveDraftHtml).toContain("advanceMockDraft('cam-bid')");
    expect(liveDraftHtml).toContain("mockAuction: currentMockDraft && currentMockDraft.auction");
    expect(liveDraftHtml).toContain("advanceMockDraft('cam-nominate', selectedTargetName, nominationPriceValue())");
    expect(liveDraftHtml).toContain("advanceMockDraft('next-cam-decision')");
    expect(liveDraftHtml).toContain("advanceMockDraft('next-round')");
    expect(liveDraftHtml).toContain("advanceMockDraft('complete-mock')");
    expect(liveDraftHtml).toContain("'Bid ' + money(mockDraft.auction.nextCamBid)");
    expect(liveDraftHtml).toContain("advanceButton.textContent = phase === 'ai-sale' ? 'Continue AI sale' : 'Advance AI Sale';");
    expect(liveDraftHtml).toContain("'Current high bid ' + money(auction.resolution.price) + ' - AI sale will continue automatically'");
    expect(liveDraftHtml).toContain("const canPass = isMockMode && (phase === 'human-decision' || phase === 'ai-sale');");
    expect(liveDraftHtml).toContain("byId('mock-pass-button').textContent = 'Pass';");
    expect(liveDraftHtml).toContain("scheduleMockAutoAdvance(mockDraft);");
    expect(liveDraftHtml).toContain("const mockAuctionResolutionEvents = auction =>");
    expect(liveDraftHtml).toContain("const mockAuctionCamBidEvents = mockDraft =>");
    expect(liveDraftHtml).toContain("await animateMockAuctionResolution();");
    expect(liveDraftHtml).toContain("await animateMockCamBid();");
    expect(liveDraftHtml).toContain("action === 'cam-bid'");
    expect(liveDraftHtml).toContain("['advance', 'pass'].includes(action)");
    expect(liveDraftHtml).toContain("action === 'complete-mock'");
    expect(liveDraftHtml).toContain("completeButton.textContent = 'Completing mock...'");
    expect(liveDraftHtml).toContain("mockDraftItem('Completing mock', 'Simulating the remaining auction and writing the completed practice log.')");
    expect(liveDraftHtml).toContain("nextDecisionButton.textContent = mockAdvanceRequestAction === 'next-cam-decision' ? 'Simming to Cam...' : 'Sim to Cam action';");
    expect(liveDraftHtml).toContain("nextRoundButton.textContent = 'Sim to next round';");
    expect(liveDraftHtml).toContain("completeButton.textContent = mockAdvanceRequestAction === 'complete-mock' ? 'Completing mock...' : 'Complete mock draft';");
    expect(liveDraftHtml).toContain("completeButton.disabled = mockAdvanceBusy || !isMockMode || terminal;");
    expect(liveDraftHtml).toContain("if (data.availableTargets && data.owners) render(data);");
    expect(liveDraftHtml).toContain("if (data.mockBatchJob && data.mockBatchJob.result) {");
    expect(liveDraftHtml).toContain("window.location.assign('/mock-results');");
    expect(liveDraftHtml).toContain("else await refreshMockDraft();");
    expect(liveDraftHtml).toContain("mockAuctionFeedLines(mockDraft)");
    expect(liveDraftHtml).toContain("className = 'mock-feed-line ' + event.type");
    expect(liveDraftHtml).toContain("mockDraftItem('Current nomination'");
    expect(liveDraftHtml).toContain("mockDraftItem('Top AI bids'");
    expect(liveDraftHtml).toContain("recommended + ' now / ' + topAiOwner + ' can chase to ' + topAiBid + ' / Cam max ' + maxBid");
    expect(liveDraftHtml).toContain("currentDraftMode === 'interactive-mock'");
    expect(liveDraftHtml).toContain("Mock mode - use auction controls");
    expect(liveDraftHtml).toContain("Mock auction sold ");
    expect(liveDraftHtml).toContain("Manual sale logging is disabled here.");
    expect(liveDraftHtml).not.toContain("'AI sale ready at ' + money(auction.currentBid)");
    expect(liveDraftHtml).toContain("if (currentDraftMode === 'interactive-mock') focusCommandInput();");
    expect(liveDraftHtml).toContain("mode: currentDraftMode");
    expect(liveDraftHtml).toContain("mode=' + currentDraftMode");
    expect(liveDraftHtml).toContain("let currentDraftSession = 'live'");
    expect(liveDraftHtml).toContain("const sessionQuery = () => '&draftSession=' + encodeURIComponent(currentDraftSession)");
    expect(liveDraftHtml).toContain("draftSession: currentDraftSession");
    expect(liveDraftHtml).toContain("const normalizeDraftSession = (value, mode = currentDraftMode, strategyKey = currentStrategyKey) =>");
    expect(liveDraftHtml).toContain("if (session.startsWith('scratch:')) return session;");
    expect(liveDraftHtml).toContain("const draftModeForSession = (session, mode) =>");
    expect(liveDraftHtml).toContain("currentDraftMode = draftModeForSession(currentDraftSession, currentDraftMode);");
    expect(liveDraftHtml).toContain("currentDraftSession = normalizeDraftSession(parsed.session, currentDraftMode, currentStrategyKey);");
    expect(liveDraftHtml).toContain("currentDraftSession = normalizeDraftSession(draftSession, currentDraftMode, currentStrategyKey);");
    expect(liveDraftHtml).toContain("const renderStateLoadError = message =>");
    expect(liveDraftHtml).toContain("renderStateLoadError(state.error || 'Could not load draft room.');");
    expect(liveDraftHtml).toContain("const setDraftSession = async draftSession =>");
    expect(liveDraftHtml).toContain("const guardDraftModeSwitch = nextMode =>");
    expect(liveDraftHtml).toContain("if (nextMode === currentDraftMode && (isActiveDraft() || isStartingDraft())) return false;");
    expect(liveDraftHtml).toContain("window.alert('End the active draft before switching draft modes.');");
    expect(liveDraftHtml).toContain("const openScratchSession = async () =>");
    expect(liveDraftHtml).toContain("syncDraftSession(state)");
    expect(liveDraftHtml).toContain("const draftNightLockFor = state =>");
    expect(liveDraftHtml).toContain("Live session locked");
    expect(liveDraftHtml).toContain("if (draftNightLockFor(currentState))");
    expect(liveDraftHtml).toContain("byId('header-board-search').hidden = true;");
    expect(liveDraftHtml).not.toContain("byId('header-board-search').hidden = !isActiveDraft();");
    expect(liveDraftHtml).not.toContain("startMock.disabled = locked");
    expect(liveDraftHtml).toContain("aria-label=\"Confirm start draft\" hidden>Start draft");
    expect(liveDraftHtml).toContain("aria-label=\"End active draft\" hidden>End draft");
    expect(liveDraftHtml).toContain("byId('confirm-start-draft-button').addEventListener('click', () => beginDraftCountdown())");
    expect(liveDraftHtml).toContain("byId('end-draft-button').addEventListener('click', () => endActiveDraft())");
    expect(liveDraftHtml).toContain("aria-label=\"Open app menu\"");
    expect(liveDraftHtml).toContain("data-menu-label=\"Real draft\"");
    expect(liveDraftHtml).toContain("data-menu-label=\"Mock draft\"");
    expect(liveDraftHtml).toContain("data-menu-label=\"My expert\"");
    expect(liveDraftHtml).toContain("data-menu-label=\"Player news\"");
    expect(liveDraftHtml).toContain("item.setAttribute('aria-current', 'page')");
    expect(liveDraftHtml).toContain("item.removeAttribute('aria-current')");
    expect(liveDraftHtml).toContain("byId('start-real-draft-button').addEventListener('click', () => openDraftRoomMode('real'))");
    expect(liveDraftHtml).toContain("byId('start-mock-draft-button').addEventListener('click', () => openDraftRoomMode('interactive-mock'))");
    expect(liveDraftHtml).toContain("byId('draft-mode-real-button').addEventListener('click', () => openDraftRoomMode('real'))");
    expect(liveDraftHtml).toContain("byId('draft-mode-mock-button').addEventListener('click', () => openDraftRoomMode('interactive-mock'))");
    expect(liveDraftHtml).toContain("byId('header-export-json-button').addEventListener('click', () => exportLog('json'))");
    expect(liveDraftHtml).toContain("byId('header-export-csv-button').addEventListener('click', () => exportLog('csv'))");
    expect(liveDraftHtml).toContain("byId('header-export-bundle-button').addEventListener('click', () => exportSessionBundle())");
    expect(liveDraftHtml).toContain("byId('header-import-log-button').addEventListener('click', () => byId('import-log-file').click())");
    expect(liveDraftHtml).toContain("const undoDraftRoom = async () =>");
    expect(liveDraftHtml).toContain("byId('header-undo-button').addEventListener('click', () => undoDraftRoom())");
    expect(liveDraftHtml).toContain("byId('header-reset-button').addEventListener('click', () => resetDraftRoom())");
    expect(liveDraftHtml).toContain("if (!guardDraftModeSwitch(nextMode)) return;");
    expect(liveDraftHtml).toContain("await setDraftMode(mode, { prepareStart: true });");
    expect(liveDraftHtml).toContain("Run mocks");
    expect(liveDraftHtml).toContain("Run new mocks");
    expect(liveDraftHtml).toContain("Mock results");
    expect(liveDraftHtml).toContain("Mock Results");
    expect(liveDraftHtml).toContain("Best W1");
    expect(liveDraftHtml).toContain("' - season rank ' + team.projectedFinishLabel");
    expect(liveDraftHtml).toContain("Season Rankings");
    expect(liveDraftHtml).toContain("Season");
    expect(liveDraftHtml).toContain("Season parts");
    expect(liveDraftHtml).toContain("Starters");
    expect(liveDraftHtml).toContain("Depth");
    expect(liveDraftHtml).toContain("Consistency");
    expect(liveDraftHtml).toContain("textElement('span', 'Rank')");
    expect(liveDraftHtml).toContain("textElement('span', 'Owner')");
    expect(liveDraftHtml).toContain("textElement('span', 'Week 1')");
    expect(liveDraftHtml).not.toContain("ranking.explanation + ' W1 #'");
    expect(liveDraftHtml).not.toContain("Top score");
    expect(liveDraftHtml).toContain("grid-template-columns: repeat(5, minmax(220px, 1fr));");
    expect(liveDraftHtml).toContain("@media (max-width: 1200px)");
    expect(liveDraftHtml).toContain("@media (max-width: 1160px)");
    expect(liveDraftHtml).toContain(".app {\n        grid-template-columns: 1fr;\n        grid-template-rows: auto auto auto;\n        height: auto;\n        overflow: visible;\n      }");
    expect(liveDraftHtml).toContain(".workspace {\n        grid-column: 1;\n        grid-row: auto;");
    expect(liveDraftHtml).toContain("height: auto;\n        min-height: 100vh;\n        overflow: visible;");
    expect(liveDraftHtml).toContain(".draft-header {\n        position: sticky;\n        top: 0;\n        z-index: 60;");
    expect(liveDraftHtml).toContain(".results-grid {\n        grid-template-columns: repeat(2, minmax(0, 1fr));\n      }");
    expect(liveDraftHtml).toContain(".results-grid {\n        grid-template-columns: 1fr;\n      }");
    expect(liveDraftHtml).not.toContain("mockDraftItem('AI max bids'");
    expect(liveDraftHtml).toContain("strategyKey: currentStrategyKey");
    expect(liveDraftHtml).toContain("window.location.assign('/mock-results')");
    expect(liveDraftHtml).toContain("byId('player-news-button').addEventListener('click', () => {");
    expect(liveDraftHtml).toContain("window.location.assign(playerNewsRouteUrl())");
    expect(liveDraftHtml).toContain("byId('my-expert-button').addEventListener('click', () => {");
    expect(liveDraftHtml).toContain("window.location.assign(myExpertRouteUrl())");
    expect(liveDraftHtml).toContain("byId('my-expert-refresh-button').addEventListener('click', () => refreshMyExpertIfCurrentRoute())");
    expect(liveDraftHtml).toContain("byId('player-news-status').textContent = playerNewsUpdatedLabel(latestPlayerNewsFeed)");
    expect(liveDraftHtml).toContain("byId('player-news-refresh-button').addEventListener('click', () => refreshPlayerNewsIfCurrentRoute({ background: true }))");
    expect(liveDraftHtml).toContain("byId('app-menu-button').addEventListener('click'");
    expect(liveDraftHtml).toContain("closeAppMenu()");
    expect(liveDraftHtml).toContain("byId('mock-results-run-new-button').addEventListener('click', () => runMockBatch())");
    expect(liveDraftHtml).toContain("byId('mock-results-run-button').textContent = 'No runs yet'");
    expect(liveDraftHtml).toContain("byId('mock-results-run-button').disabled = true");
    expect(liveDraftHtml).toContain("button.disabled = !selectedRun");
    expect(liveDraftHtml).toContain("if (byId('mock-results-run-button').disabled) return;");
    expect(liveDraftHtml).toContain("script: mockBatchScript()");
    expect(liveDraftHtml).toContain("Build around Hampton:46-52:2; target Zay max $31");
    expect(liveDraftHtml).toContain("'Build around'");
    expect(liveDraftHtml).toContain("latestMockBatchReport.script.buildAround");
    expect(liveDraftHtml).toContain("const buildAroundOutcomeText = outcome =>");
    expect(liveDraftHtml).toContain("latestMockBatchReport.script.buildAroundOutcomes");
    expect(liveDraftHtml).toContain("'Price sweep'");
    expect(liveDraftHtml).toContain("bestBuildAroundOutcomeFor(buildAroundOutcomes)");
    expect(liveDraftHtml).toContain("outcome.minimumSalePrice || outcome.maximumSalePrice");
    expect(liveDraftHtml).toContain("outcome.averageOwnerWeek1WhenDrafted");
    expect(liveDraftHtml).toContain("' / Season ' + scoreText(outcome.averageOwnerSeasonStrengthWhenDrafted)");
    expect(liveDraftHtml).toContain("const renderPositionMarket = state =>");
    expect(liveDraftHtml).not.toContain("const renderOwnerNeeds = state =>");
    expect(liveDraftHtml).toContain("const renderShortlist = state =>");
    expect(liveDraftHtml).toContain("const renderPositionContext = state =>");
    expect(liveDraftHtml).toContain("const renderReadiness = state =>");
    expect(liveDraftHtml).toContain("const renderPostDraftAudit = state =>");
    expect(liveDraftHtml).toContain("state.postDraftAudit");
    expect(liveDraftHtml).toContain("'Mock ' + mockRangeText(audit.mockRange)");
    expect(liveDraftHtml).toContain("audit.verdict");
    expect(liveDraftHtml).toContain("const renderImportConflictReview = state =>");
    expect(liveDraftHtml).toContain("state.conflictReview");
    expect(liveDraftHtml).toContain("issue.matchOptions");
    expect(liveDraftHtml).toContain("Import needs review");
    expect(liveDraftHtml).toContain("const renderDraftPath = state =>");
    expect(liveDraftHtml).toContain("state.draftPath");
    expect(liveDraftHtml).toContain("let activeSidePanel = 'lineup'");
    expect(liveDraftHtml).toContain("const renderSidePanel = state =>");
    expect(liveDraftHtml).toContain("const setSidePanel = panel =>");
    expect(liveDraftHtml).toContain("panel.hidden = panel.dataset.sidePanelView !== activeSidePanel");
    expect(liveDraftHtml).toContain("const selectTargetForSale = target =>");
    expect(liveDraftHtml).toContain("setSidePanel('lineup')");
    expect(liveDraftHtml).toContain("byId('add-price').focus()");
    expect(liveDraftHtml).toContain("const shortlistStorageKey = () =>");
    expect(liveDraftHtml).toContain("window.localStorage");
    expect(liveDraftHtml).toContain("const toggleShortlist = target =>");
    expect(liveDraftHtml).toContain("const starTargetButton = target =>");
    expect(liveDraftHtml).toContain("className = 'star-button'");
    expect(liveDraftHtml).toContain("justify-content: space-between;");
    expect(liveDraftHtml).toContain("width: 100%;");
    expect(liveDraftHtml).toContain("title.append(textElement('div', target.name, 'player-name'), starTargetButton(target));");
    expect(liveDraftHtml).not.toContain("title.append(starTargetButton(target), textElement('div', target.name, 'player-name'));");
    expect(liveDraftHtml).toContain("const visibleBoardTargets = state =>");
    expect(liveDraftHtml).toContain("state.keeperTargets");
    expect(liveDraftHtml).toContain("const realDraftHasStarted = state => currentDraftMode === 'real' && (isActiveDraft() || state.events.length > 0)");
    expect(liveDraftHtml).toContain("target.draftable === false");
    expect(liveDraftHtml).toContain("row.classList.add('keeper-row')");
    expect(liveDraftHtml).toContain("target.keeperOwner + ' keeper'");
    expect(liveDraftHtml).toContain("button.disabled = true");
    expect(liveDraftHtml).toContain("Path");
    expect(liveDraftHtml).toContain("Target");
    expect(liveDraftHtml).toContain("Pivot");
    expect(liveDraftHtml).toContain("Risk");
    expect(liveDraftHtml).toContain("Dead zone");
    expect(liveDraftHtml).toContain("path.riskAlerts");
    expect(liveDraftHtml).toContain("strategyCoach");
    expect(liveDraftHtml).toContain("slot.fallbackPriceBand");
    expect(liveDraftHtml).toContain("slot.fallbackNames");
    expect(liveDraftHtml).toContain("<option value=\"valueGap\">Best value gap</option>");
  });

  it("uses a dark dashboard shell with command rail and panel grouping", () => {
    expect(liveDraftHtml).toContain("color-scheme: dark;");
    expect(liveDraftHtml).toContain("--bg: #02070d;");
    expect(liveDraftHtml).toContain("--nav-rail-width: 356px;");
    expect(liveDraftHtml).toContain("--global-menu-width: 260px;");
    expect(liveDraftHtml).toContain("--global-menu-height: 72px;");
    expect(liveDraftHtml).toContain("html {");
    expect(liveDraftHtml).toContain("background: var(--bg);");
    expect(liveDraftHtml).toContain("min-width: 100vw;");
    expect(liveDraftHtml).toContain("grid-template-columns: var(--nav-rail-width) minmax(0, 1fr);");
    expect(liveDraftHtml).toContain("grid-template-rows: var(--global-menu-height) minmax(0, 1fr);");
    expect(liveDraftHtml).toContain("height: 100vh;");
    expect(liveDraftHtml).toContain(".sidebar {");
    expect(liveDraftHtml).toContain("padding: 18px 22px 20px;");
    expect(liveDraftHtml).toContain("overflow-y: auto;");
    expect(liveDraftHtml).toContain(".workspace {");
    expect(liveDraftHtml).toContain("width: var(--global-menu-width);");
    expect(liveDraftHtml).toContain(".app-header-menu-slot .global-app-menu {\n      position: static;");
    expect(liveDraftHtml).toContain(".draft-title-group {");
    expect(liveDraftHtml).toContain("justify-self: center;");
    expect(liveDraftHtml).toContain("padding: 0 24px;");
    expect(liveDraftHtml).not.toContain("padding: 0 24px 0 var(--nav-rail-width);");
    expect(liveDraftHtml).toContain("min-height: var(--global-menu-height);");
    expect(liveDraftHtml).toContain(".results-view {");
    expect(liveDraftHtml).toContain("width: 100%;");
    expect(liveDraftHtml).toContain("overflow-x: clip;");
    expect(liveDraftHtml).toContain(".results-header {\n      position: fixed;");
    expect(liveDraftHtml).toContain("top: 0;");
    expect(liveDraftHtml).toContain("left: 0;");
    expect(liveDraftHtml).toContain("right: 0;");
    expect(liveDraftHtml).toContain("z-index: 80;");
    expect(liveDraftHtml).toContain("padding: calc(var(--global-menu-height) + 18px) 24px 28px;");
    expect(liveDraftHtml).toContain("background: var(--bg);");
    expect(liveDraftHtml).toContain(".sidebar-section {");
    expect(liveDraftHtml).not.toContain(".window-controls {");
    expect(liveDraftHtml).not.toContain(".window-dot");
    expect(liveDraftHtml).toContain(".board-panel {");
    expect(liveDraftHtml).toContain(".decision-panel {");
    expect(liveDraftHtml).toContain(".board-table {");
    expect(liveDraftHtml).toContain("width: max-content;");
    expect(liveDraftHtml).toContain("min-width: 990px;");
    expect(liveDraftHtml).toContain(".scroll {\n      overflow: auto;\n      scrollbar-width: none;");
    expect(liveDraftHtml).toContain(".scroll::-webkit-scrollbar {\n      width: 0;\n      height: 0;");
    expect(liveDraftHtml).toContain(".board-table th:first-child,");
    expect(liveDraftHtml).toContain(".board-table td:nth-child(2)");
    expect(liveDraftHtml).toContain("left: 42px;");
    expect(liveDraftHtml).toContain("box-shadow: 12px 0 18px rgba(0, 0, 0, 0.18);");
    expect(liveDraftHtml).toContain(".board-table tbody tr:hover > td:first-child");
    expect(liveDraftHtml).toContain("overflow-wrap: normal;");
    expect(liveDraftHtml).toContain("white-space: nowrap;");
    expect(liveDraftHtml).toContain(".player-news-headline {");
    expect(liveDraftHtml).toContain("overflow-wrap: anywhere;");
    expect(liveDraftHtml).toContain(".player-news-layout {");
    expect(liveDraftHtml).toContain("grid-template-columns: minmax(0, 1fr);");
    expect(liveDraftHtml).toContain(".player-news-view .results-main {");
    expect(liveDraftHtml).toContain("max-width: 1520px;");
    expect(liveDraftHtml).toContain("margin: 0 auto;");
    expect(liveDraftHtml).toContain("padding-right: 32px;");
    expect(liveDraftHtml).toContain(".player-news-toolbar {");
    expect(liveDraftHtml).toContain("grid-template-columns: minmax(220px, 1fr) 160px 150px 170px 112px;");
    expect(liveDraftHtml).toContain("top: 72px;");
    expect(liveDraftHtml).toContain("z-index: 70;");
    expect(liveDraftHtml).toContain("#player-news-status {");
    expect(liveDraftHtml).toContain("min-width: 112px;");
    expect(liveDraftHtml).toContain("text-overflow: ellipsis;");
    expect(liveDraftHtml).toContain(".player-news-side {");
    expect(liveDraftHtml).toContain("grid-template-columns: repeat(2, minmax(0, 1fr));");
    expect(liveDraftHtml).toContain(".player-news-source-stack {");
    expect(liveDraftHtml).toContain(".player-news-filter-options {");
    expect(liveDraftHtml).toContain("max-height: 240px;");
    expect(liveDraftHtml).toContain(".player-news-date {");
    expect(liveDraftHtml).toContain(".player-news-date-chip {");
    expect(liveDraftHtml).toContain(".player-news-source {");
    expect(liveDraftHtml).toContain("word-break: break-word;");
  });

  it("adds purposeful dashboard color accents to draft-room controls", () => {
    expect(liveDraftHtml).toContain("--pos-rb: #5ba8ff;");
    expect(liveDraftHtml).toContain("--pos-wr: #ad8cff;");
    expect(liveDraftHtml).toContain("--pos-te: #19e49c;");
    expect(liveDraftHtml).toContain("--pos-qb: #ff8845;");
    expect(liveDraftHtml).toContain("const positionClassFor = position => 'position-' + safeClassPart(position || 'unknown');");
    expect(liveDraftHtml).toContain("row.classList.add(positionClassFor(target.position));");
    expect(liveDraftHtml).toContain("pill.className = 'market-pill ' + positionClassFor(position);");
    expect(liveDraftHtml).toContain("item.className = 'strategy-value strategy-' + strategyKey");
    expect(liveDraftHtml).toContain("const tagClassFor = label =>");
    expect(liveDraftHtml).toContain("--position-row-bg: rgba(91, 168, 255, 0.1);");
    expect(liveDraftHtml).toContain(".board-table tbody tr[class*=\"position-\"] td:first-child");
    expect(liveDraftHtml).toContain(".board-table tbody tr[class*=\"position-\"] {\n      background: var(--position-row-bg, rgba(91, 168, 255, 0.08));");
    expect(liveDraftHtml).toContain(".board-table tbody tr[class*=\"position-\"] > td:first-child");
    expect(liveDraftHtml).toContain("background: var(--position-sticky-bg, #081826);");
    expect(liveDraftHtml).toContain("border: 1px solid var(--position-accent-line, rgba(91, 168, 255, 0.68));");
    expect(liveDraftHtml).toContain("background: #06101a;");
    expect(liveDraftHtml).toContain(".filter-chip:not([data-position-filter=\"ALL\"])::before");
    expect(liveDraftHtml).toContain(".market-pill {");
  });

  it("uses the same centered app header structure on secondary routes", () => {
    expect(liveDraftHtml).toContain("<header class=\"draft-header app-page-header\">");
    expect(liveDraftHtml).toContain("<header class=\"results-header app-page-header\">");
    expect(liveDraftHtml).toContain("id=\"draft-header-menu-slot\"");
    expect(liveDraftHtml).toContain("id=\"mock-results-header-menu-slot\"");
    expect(liveDraftHtml).toContain("id=\"my-expert-header-menu-slot\"");
    expect(liveDraftHtml).toContain("id=\"player-news-header-menu-slot\"");
    expect(liveDraftHtml).toContain(".app-header-menu-slot .brand {\n      display: none;\n    }");
    expect(liveDraftHtml).toContain("'my-expert': 'my-expert-header-menu-slot'");
    expect(liveDraftHtml).toContain("'player-news': 'player-news-header-menu-slot'");
    expect(liveDraftHtml).toContain("setActiveRouteShell('my-expert')");
    expect(liveDraftHtml).toContain("setActiveRouteShell('player-news')");
    expect(liveDraftHtml).toContain("padding: 0 24px;");
    expect(liveDraftHtml).not.toContain("padding: 0 24px 0 var(--global-menu-width);");
    expect(liveDraftHtml).not.toContain("body[data-active-route=\"draft-room\"] > .global-app-menu");
    expect(liveDraftHtml).not.toContain("document.body.insertBefore(appMenu, byId('draft-room-view'))");
  });

  it("renders raw sale history and import/export draft-log actions", () => {
    expect(liveDraftHtml).toContain("className = 'raw-command'");
    expect(liveDraftHtml).toContain("event.input");
    expect(liveDraftHtml).toContain("exportLog('json')");
    expect(liveDraftHtml).toContain("exportLog('csv')");
    expect(liveDraftHtml).toContain("const exportSessionBundle = async () =>");
    expect(liveDraftHtml).toContain("fetch('/api/export-bundle?mode=' + currentDraftMode + '&strategy=' + currentStrategyKey + sessionQuery())");
    expect(liveDraftHtml).toContain("downloadText('mockd-' + safeFilePart(currentDraftSession) + '-' + currentDraftMode + '-bundle.json'");
    expect(liveDraftHtml).toContain("importDraftLogFile");
    expect(liveDraftHtml).toContain("postJson('/api/import'");
    expect(liveDraftHtml).toContain("confirmLiveDraftMutation");
    expect(liveDraftHtml).toContain("expectedCommandCount: currentCommandCount()");
    expect(liveDraftHtml).toContain("confirmUndo: true");
    expect(liveDraftHtml).toContain("confirmImport: true");
    expect(liveDraftHtml).toContain("confirmReset: true");
  });

  it("returns keyboard focus to the quick-sale command entry after sales", () => {
    expect(liveDraftHtml).toContain("const focusCommandInput = () =>");
    expect(liveDraftHtml).toContain("byId('quick-sale-command').focus()");
    expect(liveDraftHtml).toContain("focusCommandInput();");
  });

  it("uses a custom select arrow with enough right-side spacing", () => {
    expect(liveDraftHtml).toContain("select {");
    expect(liveDraftHtml).toContain("appearance: none;");
    expect(liveDraftHtml).toContain("padding-right: 34px;");
    expect(liveDraftHtml).toContain("background-position: right 12px center;");
  });

  it("keeps room-wide budget metrics out of the visible draft workspace", () => {
    expect(liveDraftHtml).not.toContain("id=\"metrics\"");
    expect(liveDraftHtml).not.toContain("renderMetrics");
    expect(liveDraftHtml).not.toContain("state.room.liveInflationFactor.toFixed(2) + 'x'");
    expect(liveDraftHtml).not.toContain("String(state.room.remainingRosterSlots)");
    expect(liveDraftHtml).not.toContain("state.room.saleVsExpected");
    expect(liveDraftHtml).not.toContain("state.watchOwner.budgetRemaining)]");
    expect(liveDraftHtml).not.toContain("state.watchOwner.maxBid)]");
    expect(liveDraftHtml).not.toContain("grid-template-columns: repeat(5, minmax(120px, 1fr));");
    expect(liveDraftHtml).not.toContain("Room Left");
  });

  it("generates parseable build-around scripts for inflated live values above the cap", () => {
    const script = buildAroundScriptFromLiveUi({
      name: "Elite RB",
      liveExpectedPrice: 100,
      expectedPrice: 72,
      personalValue: 80,
      recommendedMaxBid: 80,
    });

    expect(script).toBe("Build around Elite RB:74-80:2");
    expect(parseMockDraftScript(script)).toMatchObject({
      buildAround: {
        owner: "Cam",
        player: "Elite RB",
        prices: [74, 76, 78, 80],
      },
    });
  });

  it("switches the board from the dense table to player cards on compact screens", () => {
    expect(liveDraftHtml).toContain("@media (max-width: 760px)");
    expect(liveDraftHtml).toContain(".scroll {\n        display: none;\n      }");
    expect(liveDraftHtml).toContain(".board-cards {\n        display: block;\n      }");
    expect(liveDraftHtml).toContain("className = 'target-card ' + positionClassFor(target.position)");
    expect(liveDraftHtml).toContain("className = 'target-card-values'");
  });
});
