import { afterEach, describe } from "vitest";
import { registerRequestLimitTests } from "./liveDraftServer/requestLimits.js";
import { registerRequestRoutingTests } from "./liveDraftServer/requestRouting.js";
import { registerDraftStateTests } from "./liveDraftServer/draftState.js";
import { registerRealMockSaleTests } from "./liveDraftServer/realMockSale.js";
import { registerModeAndStrategyTests } from "./liveDraftServer/modesAndStrategies.js";
import { registerDestructiveActionTests } from "./liveDraftServer/destructiveActions.js";
import { registerSaleConcurrencyTests } from "./liveDraftServer/saleConcurrency.js";
import { registerSessionTests } from "./liveDraftServer/sessions.js";
import { registerSessionLockTests } from "./liveDraftServer/sessionLocks.js";
import { registerTransferTests } from "./liveDraftServer/transfer.js";
import { registerInteractiveAuctionTests } from "./liveDraftServer/interactiveAuction.js";
import { registerInteractiveSpeedTests } from "./liveDraftServer/interactiveSpeed.js";
import { registerInteractiveJobTests } from "./liveDraftServer/interactiveJobs.js";
import { registerCapacityTests } from "./liveDraftServer/capacity.js";
import { registerResultTests } from "./liveDraftServer/results.js";
import { registerOptimizedResultTests } from "./liveDraftServer/optimizedResults.js";
import { registerScriptTests } from "./liveDraftServer/scripts.js";
import { registerNewsTests } from "./liveDraftServer/news.js";
import { registerAdviceTests } from "./liveDraftServer/advice.js";
import { registerSyncTests } from "./liveDraftServer/sync.js";
import { registerNewsFallbackTests } from "./liveDraftServer/newsFallback.js";
import { closeTestServers } from "./liveDraftServer/support/serverHarness.js";

describe("live draft server", () => {
  afterEach(closeTestServers);

  registerRequestLimitTests();
  registerRequestRoutingTests();
  registerDraftStateTests();
  registerRealMockSaleTests();
  registerModeAndStrategyTests();
  registerDestructiveActionTests();
  registerSaleConcurrencyTests();
  registerSessionTests();
  registerSessionLockTests();
  registerTransferTests();
  registerInteractiveAuctionTests();
  registerInteractiveSpeedTests();
  registerInteractiveJobTests();
  registerCapacityTests();
  registerResultTests();
  registerOptimizedResultTests();
  registerScriptTests();
  registerNewsTests();
  registerAdviceTests();
  registerSyncTests();
  registerNewsFallbackTests();
});
