import { describe, expect, it } from "vitest";
import { platformShellHtml } from "../src/platform/platformShellUi.js";

describe("platform shell UI", () => {
  it("ships a cookie-backed auth shell and unified product frame", () => {
    expect(platformShellHtml).toContain("id=\"auth-panel\"");
    expect(platformShellHtml).toContain("id=\"app-shell\"");
    expect(platformShellHtml).toContain("GET /session");
    expect(platformShellHtml).toContain("fetch(\"/sessions\"");
    expect(platformShellHtml).toContain("fetch(\"/accounts\"");
    expect(platformShellHtml).toContain("fetch(\"/session\", { method: \"DELETE\" })");
    expect(platformShellHtml).toContain("Live draft room");
    expect(platformShellHtml).toContain("href=\"/draft-room\"");
    expect(platformShellHtml).toContain("Commissioner setup");
    expect(platformShellHtml).toContain("href=\"/setup\"");
    expect(platformShellHtml).toContain("id=\"setup-season-id-input\"");
    expect(platformShellHtml).toContain("id=\"setup-rows-input\"");
    expect(platformShellHtml).toContain("id=\"setup-preview-button\"");
    expect(platformShellHtml).toContain("id=\"setup-apply-button\"");
    expect(platformShellHtml).toContain("/setup-import/preview");
    expect(platformShellHtml).toContain("/setup-import/apply");
    expect(platformShellHtml).toContain("id=\"setup-blockers\"");
    expect(platformShellHtml).toContain("id=\"setup-pending-invites\"");
    expect(platformShellHtml).toContain("pending invites");
    expect(platformShellHtml).toContain("id=\"season-id-input\"");
    expect(platformShellHtml).toContain("id=\"load-season-button\"");
    expect(platformShellHtml).toContain("id=\"team-claim-list\"");
    expect(platformShellHtml).toContain("id=\"room-id-input\"");
    expect(platformShellHtml).toContain("id=\"open-room-button\"");
    expect(platformShellHtml).toContain("id=\"create-room-button\"");
    expect(platformShellHtml).toContain("id=\"start-room-button\"");
    expect(platformShellHtml).toContain("id=\"sale-command-input\"");
    expect(platformShellHtml).toContain("id=\"log-sale-button\"");
    expect(platformShellHtml).toContain("id=\"undo-sale-button\"");
    expect(platformShellHtml).toContain("id=\"end-room-button\"");
    expect(platformShellHtml).toContain("id=\"create-export-artifact-button\"");
    expect(platformShellHtml).toContain("id=\"artifact-download-link\"");
    expect(platformShellHtml).toContain("id=\"artifact-preview\"");
    expect(platformShellHtml).toContain("const defaultSeasonId = \"league-214674-season-2026\"");
    expect(platformShellHtml).toContain("const defaultPlayerCatalog");
    expect(platformShellHtml).toContain("Puka Nacua");
    expect(platformShellHtml).toContain("fetch(seasonEndpoint()");
    expect(platformShellHtml).toContain("/team-claims");
    expect(platformShellHtml).toContain("fetch(\"/live-rooms\"");
    expect(platformShellHtml).toContain("fetch(roomEndpoint()");
    expect(platformShellHtml).toContain("fetch(roomEndpoint(\"start\")");
    expect(platformShellHtml).toContain("fetch(roomEndpoint(\"sales\")");
    expect(platformShellHtml).toContain("fetch(roomEndpoint(\"undo\")");
    expect(platformShellHtml).toContain("fetch(roomEndpoint(\"end\")");
    expect(platformShellHtml).toContain("fetch(roomEndpoint(\"export-artifacts\")");
    expect(platformShellHtml).toContain("fetch(roomEndpoint(\"events\")");
    expect(platformShellHtml).toContain("new EventSource(roomEndpoint(\"event-stream\")");
    expect(platformShellHtml).not.toContain("href=\"/mock-draft\"");
    expect(platformShellHtml).not.toContain("href=\"/prep\"");
    expect(platformShellHtml).not.toContain("Open mocks");
    expect(platformShellHtml).not.toContain("Open prep");
  });
});
