import { leagueConfig, ownerOrder } from "../../../config/league.js";
import { AuctionEngineConfig } from "./configContracts.js";
import { configuredRosterMaximums, defaultSeed, defaultStarterMinimums } from "./constants.js";

export const defaultAuctionEngineConfig: AuctionEngineConfig = {
  owners: ownerOrder,
  auctionBudget: leagueConfig.auctionBudget,
  rosterSize: leagueConfig.rosterSize,
  rosterMaximums: configuredRosterMaximums(),
  starterMinimums: defaultStarterMinimums(),
  flexMinimum: leagueConfig.lineup.FLEX,
  minimumBid: 1,
  reservePriceRatio: 0.75,
  ownerDemandMultipliers: {},
  ownerBehaviors: {},
  ownerRosterMaximums: {},
  ownerPositionAnchorTargets: {},
  ownerPositionCoreTargets: {},
  ownerPositionCoreMaxBids: {},
  ownerPositionSlotMaxBids: {},
  ownerPositionCoreBudgetEnvelopes: {},
  ownerPlayerTargetMaxBids: {},
  positionOverbidDamping: {
    QB: 0.75,
    WR: 0.4,
    TE: 0.65,
  },
  scarcity: {
    comparablePriceRatio: 0.8,
    minimumComparablePrice: 5,
    bidderDepthWeight: 0.35,
    maxDemandSlotsPerOwner: 2,
    slope: 0.03,
    maxMultiplier: 1.08,
  },
  rosterNeed: {
    missingStarterMultiplier: 1.03,
    missingFlexMultiplier: 1.015,
    emptyPremiumPositionMultiplier: 1,
    benchQuarterbackMultiplier: 0.75,
    benchTightEndMultiplier: 0.65,
    specialTeamsBenchMultiplier: 0.85,
    lastPositionSlotMultiplier: 0.97,
  },
  nomination: {
    earlyEliteBiasPicks: 6,
    earlyMarketPriceWeight: 2,
    marketPriceWeight: 1.05,
    projectionWeight: 0.15,
    ownerNeedWeight: 1.8,
    opponentNeedWeight: 0.45,
    affordabilityWeight: 0.35,
    scarcityWeight: 0.45,
    flushMoneyWeight: 0.5,
    tieBreakWeight: 0.001,
  },
  endgameSpend: {
    startRosterSlotsRemaining: 4,
    targetBudgetPerSlot: 12,
    slope: 0.18,
    maxMultiplier: 1.25,
  },
  roomPressure: {
    startRosterSlotsRemaining: 14,
    minRosterSlotsRemainingExclusive: 4,
    targetBudgetPerSlot: 12,
    slope: 0.35,
    maxMultiplier: 1.1,
    minimumPlayerPrice: 30,
    maximumPlayerPrice: 60,
  },
  competitionPressure: {
    minimumPlayerPrice: 30,
    anchorPriceRatio: 0.8,
    missingStarterSlope: 0.08,
    missingFlexSlope: 0.04,
    maxRivalAnchors: 2,
    maxMultiplier: 1.12,
  },
  budgetPacing: {
    targetBudgetPerSlotAfterPurchase: 4,
    slope: 0.85,
    maxDiscount: 0.28,
    minimumPlayerPrice: 8,
  },
  bidVariance: {
    minimumPlayerPrice: 30,
    fullEffectPlayerPrice: 75,
    maxDiscount: 0.07,
    maxPremium: 0.05,
  },
  lateOpeningBid: {
    startRosterSlotsRemaining: 4,
    targetBudgetPerSlot: 1,
    maxPlayerPrice: 15,
    maxExtraBid: 6,
  },
  topEndOverbidDamping: {
    startPrice: 50,
    fullEffectPrice: 75,
    maxOverbidDiscount: 0.75,
  },
  contextPenaltyBidDamping: {
    minimumPlayerPrice: 30,
    startPenalty: 0.04,
    fullEffectPenalty: 0.1,
    maxOverbidDiscount: 0.75,
  },
  topEndSaleGuard: {
    threshold: 70,
    capBelowThresholdAt: 69,
    premiumThreshold: 72,
    capBelowPremiumThresholdAt: 74,
    eliteThreshold: 80,
    capBelowEliteThresholdAt: 79,
  },
  tierSaleGuard: {
    threshold: 40,
    capBelowThresholdAt: 39,
    strongThreshold: 60,
    capBelowStrongThresholdAt: 59,
    maxPremiumStartPrice: 55,
    maxPremiumBelowStrongThreshold: 2,
  },
  seed: defaultSeed,
};
