import type { SimulationRun } from "../../src/platform/simulations.js";

const createdAt = new Date("2026-08-09T12:00:00.000Z");
const completedAt = new Date("2026-08-09T12:01:00.000Z");

export const persistedSimulationRun = (): SimulationRun => ({
  id: "run-1",
  request: {
    id: "request-1",
    userId: "account-1",
    leagueId: "league-1",
    seasonId: "season-1",
    ownerId: "owner-1",
    teamId: "team-1",
    count: 1,
    seedPrefix: "seed",
    idempotencyKey: "simulation-1",
    strategy: {
      hardLocks: [{
        playerName: "Puka Nacua",
        price: 62,
        priceMode: "ceiling",
        auctionOwner: "Owner01",
      }],
      softTargets: [{ label: "RB value", candidatePool: ["Jahmyr Gibbs"], maxBid: 70 }],
    },
    privacyOwnerUserId: "account-1",
    inputHash: "input-hash",
    createdAt,
  },
  status: "completed",
  privacyOwnerUserId: "account-1",
  createdAt,
  startedAt: createdAt,
  completedAt,
  result: {
    runId: "run-1",
    requestId: "request-1",
    completedAt,
    runCount: 1,
    seedPrefix: "seed",
    hardLockCount: 1,
    softTargetCount: 1,
    forcedSales: [{ owner: "Owner01", player: "Puka Nacua", price: 62 }],
    summary: {
      runCount: 1,
      scenarios: [{
        key: "expected",
        label: "Expected",
        runCount: 1,
        invalidRosterCount: 0,
        averagePickCount: 224,
      }],
      players: [{
        name: "Puka Nacua",
        position: "WR",
        draftedCount: 1,
        draftedRate: 1,
        averageMarketPrice: 60,
        averageSalePrice: 62,
        minimumSalePrice: 62,
        maximumSalePrice: 62,
      }],
      owners: [{
        owner: "Owner01",
        runCount: 1,
        invalidRosterCount: 0,
        averageSpend: 200,
        minimumSpend: 200,
        maximumSpend: 200,
        averageWeek1Score: 112,
        averageWeeks1To4Score: 440,
        averageBudgetRemaining: 0,
        averagePositionSpend: { QB: 5, RB: 70, WR: 90, TE: 20, K: 5, DST: 10 },
      }],
      ownerPlayerExposure: [{
        owner: "Owner01",
        player: "Puka Nacua",
        position: "WR",
        draftedCount: 1,
        draftedRate: 1,
        averagePrice: 62,
      }],
    },
    seasonSimulation: {
      draftFormat: "auction",
      runCount: 1,
      completedCount: 1,
      seedPrefix: "seed",
      strategy: {
        rawInput: "Draft Puka under $70 and an elite RB",
        targets: [
          { playerName: "Puka Nacua", maxAuctionPrice: 70 },
          { playerName: "Jahmyr Gibbs", maxSnakeRound: 2, maxSnakeOverallPick: 20 },
        ],
        target: { playerName: "Puka Nacua", maxAuctionPrice: 70 },
        preferredPositions: [{ position: "RB", tier: "elite", targetCount: 1, maxAuctionPrice: 80 }],
        positionCaps: [{ position: "WR", maxAuctionPrice: 70, excludeNamedTargets: true }],
        pairWithPlayerName: "De'Von Achane",
        summary: "Target Puka and an elite RB.",
        warnings: ["Example warning"],
      },
      targetOutcomes: [{
        playerId: "puka-nacua",
        playerName: "Puka Nacua",
        status: "hit",
        feasible: true,
        hitCount: 1,
        hitRate: 1,
        message: "Puka was drafted.",
      }, {
        playerId: "jahmyr-gibbs",
        playerName: "Jahmyr Gibbs",
        status: "miss",
        feasible: true,
        hitCount: 0,
        hitRate: 0,
        reason: "retained_by_other_team",
        message: "Gibbs was retained.",
      }],
      targetOutcome: {
        playerId: "puka-nacua",
        playerName: "Puka Nacua",
        status: "hit",
        feasible: true,
        hitCount: 1,
        hitRate: 1,
        message: "Puka was drafted.",
      },
      preferenceOutcomes: [{
        position: "RB",
        tier: "elite",
        targetCount: 1,
        status: "hit",
        feasible: true,
        hitCount: 1,
        hitRate: 1,
        rule: {
          basis: "auction_expected_value",
          positionRankMaximum: 4,
          qualifyingPlayerIds: ["jahmyr-gibbs"],
          minimumExpectedValue: 65,
        },
        message: "Elite RB drafted.",
      }, {
        position: "WR",
        tier: "elite",
        targetCount: 1,
        status: "infeasible",
        feasible: false,
        hitCount: 0,
        hitRate: 0,
        rule: {
          basis: "snake_catalog_rank",
          positionRankMaximum: 5,
          qualifyingPlayerIds: [],
        },
        message: "No qualifying receiver was available.",
      }],
      playerExposure: [{
        playerId: "puka-nacua",
        playerName: "Puka Nacua",
        position: "WR",
        count: 1,
        rate: 1,
        averagePrice: 62,
        averagePick: 1,
      }],
      positionCounts: { WR: { total: 1, perRun: 1 } },
      runs: [{
        runNumber: 1,
        label: "Run 1",
        seed: "seed-1",
        teams: [{
          teamId: "team-1",
          teamName: "Short King",
          isUserTeam: true,
          roster: [{
            playerId: "puka-nacua",
            playerName: "Puka Nacua",
            position: "WR",
            source: "human",
            price: 62,
            overallPick: 1,
            round: 1,
            rosterSlot: "WR1",
            starter: true,
            week1Points: 17.6,
          }, {
            playerId: "jahmyr-gibbs",
            playerName: "Jahmyr Gibbs",
            position: "RB",
            source: "ai",
            rosterSlot: "RB1",
            starter: true,
            week1Points: 20,
          }, {
            playerId: "devon-achane",
            playerName: "De'Von Achane",
            position: "RB",
            source: "keeper",
            price: 50,
            rosterSlot: "RB2",
            starter: true,
            week1Points: 16,
          }],
          week1Points: 17.6,
          spent: 62,
          budgetRemaining: 138,
        }],
      }],
    },
    strategyText: "Draft Puka under $70.",
    note: "Test ceiling strategy.",
  },
});
