export const behaviorTestNames: readonly string[] = [
  "uses a descending price ladder for replacement-pool players before falling back to $1",
  "defaults replacement-pool players to one-dollar fallback prices",
  "carries full-season projections through priced and replacement auction players",
  "keeps replacement kickers and defenses at the fallback price",
  "carries context adjustment metadata from priced players into the auction pool",
  "records the rotating nominator while elite market names come off early",
  "varies the opening nominator by seed while keeping each run deterministic",
  "lets the current nominator target an affordable roster need instead of the next luxury player",
  "lets nominators attack scarce roster holes that opponents still need",
  "continues the nomination rotation after skipping owners with full rosters",
  "caps overspent owners without globally discounting the next tier",
  "keeps replacement-level player bids at the minimum bid without a late opening bump",
  "lets owner behavior tune aggression and patience separately from market anchor",
  "derives separate anchor and depth tendencies from owner build profiles",
  "applies build-style behavior differently to anchor and depth bids",
  "derives owner-specific roster maximums from backup-position history",
  "applies owner-specific roster maximums during bidding",
  "raises bids for cash-heavy owners late in the auction",
  "raises mid-auction bids for cash-heavy owners while depleted owners stay constrained",
  "raises scarcity pressure when bidders have room for multiple same-tier players",
  "does not count same-position depth that would strand required starters",
  "downweights legal backup bidders in scarcity pressure",
  "discounts bids that would strand too little budget for remaining roster slots",
  "records owner budget trajectory from initial budgets through every sold pick",
  "lets cash-heavy nominators open late depth players above anchor",
  "starts spending down leftover dollars before the final two roster slots",
  "damps only the over-anchor portion of elite bids",
  "damps quarterback overbids without changing the QB anchor",
  "discounts backup quarterback bids after an owner has a starter",
  "raises unmet starter bids when a rival can consolidate a scarce anchor",
  "damps tight end overbids without changing the TE anchor",
  "damps wide receiver overbids without changing the WR anchor",
  "can target same-position anchor counts for strategy-specific mock drafts",
  "suppresses non-target anchor bids while a position-anchor strategy is unmet",
  "caps target-position anchor bids to reserve budget for the remaining core",
  "caps target-position anchor bids by planned core slot",
  "caps later position slots so a strategy does not buy expensive depth",
  "targets named players up to a max bid without forcing the purchase",
  "lets explicit player targets override general strategy budget rails",
  "preserves a legal roster path for explicit player targets still on the board",
  "discounts backup tight end bids after an owner has a starter",
  "keeps sub-threshold anchors from crossing the high-price sale boundary",
  "keeps strong WR anchors from crossing into elite sale prices",
  "dampens over-anchor bids when sourced context evidence already penalizes the player",
  "keeps near-elite anchors from adding extra $75-plus sales",
  "keeps sub-elite anchors from adding extra $80-plus sales",
  "keeps starter-tier anchors from adding extra $40-plus sales",
  "builds valid full-roster mocks from expected keepers and owner-local budgets",
];
