import { createdAtColumn, jsonbArrayDefault, updatedAtColumn } from "../columns.js";
import type { PostgresTableDefinition } from "../types.js";

export const fantasyProsTables: readonly PostgresTableDefinition[] = [
  {
    name: "fantasy_pros_rankings",
    columns: [
      { name: "ranking_type", type: "text" },
      { name: "scoring", type: "text" },
      { name: "week", type: "integer" },
      { name: "player_id", type: "integer" },
      { name: "player_name", type: "text" },
      { name: "player_position", type: "text" },
      { name: "player_team", type: "text", nullable: true },
      { name: "yahoo_id", type: "text", nullable: true },
      { name: "rank_ecr", type: "integer" },
      { name: "rank_min", type: "integer", nullable: true },
      { name: "rank_max", type: "integer", nullable: true },
      { name: "rank_average", type: "numeric", nullable: true },
      { name: "rank_standard_deviation", type: "numeric", nullable: true },
      { name: "tier", type: "integer", nullable: true },
      { name: "position_rank", type: "text", nullable: true },
      { name: "bye_week", type: "integer", nullable: true },
      { name: "ecr_delta", type: "numeric", nullable: true },
      { name: "owned_average", type: "numeric", nullable: true },
      { name: "owned_espn", type: "numeric", nullable: true },
      { name: "owned_yahoo", type: "numeric", nullable: true },
      { name: "fetched_at", type: "timestamptz" },
      createdAtColumn,
    ],
    primaryKey: ["ranking_type", "scoring", "week", "player_id"],
    indexes: [
      { name: "fantasy_pros_rankings_type_ecr_idx", columns: ["ranking_type", "week", "rank_ecr"] },
      { name: "fantasy_pros_rankings_player_id_idx", columns: ["player_id"] },
    ],
  },
  {
    name: "fantasy_pros_projections",
    columns: [
      { name: "week", type: "integer" },
      { name: "player_id", type: "integer" },
      { name: "player_name", type: "text" },
      { name: "player_position", type: "text" },
      { name: "player_team", type: "text", nullable: true },
      { name: "points", type: "numeric", nullable: true },
      { name: "points_ppr", type: "numeric", nullable: true },
      { name: "passing_yards", type: "numeric", nullable: true },
      { name: "passing_touchdowns", type: "numeric", nullable: true },
      { name: "interceptions", type: "numeric", nullable: true },
      { name: "rushing_yards", type: "numeric", nullable: true },
      { name: "rushing_touchdowns", type: "numeric", nullable: true },
      { name: "receptions", type: "numeric", nullable: true },
      { name: "receiving_yards", type: "numeric", nullable: true },
      { name: "receiving_touchdowns", type: "numeric", nullable: true },
      { name: "fetched_at", type: "timestamptz" },
      createdAtColumn,
    ],
    primaryKey: ["week", "player_id"],
    indexes: [
      { name: "fantasy_pros_projections_week_position_idx", columns: ["week", "player_position"] },
    ],
  },
  {
    name: "fantasy_pros_players",
    columns: [
      { name: "player_id", type: "integer" },
      { name: "player_name", type: "text" },
      { name: "first_name", type: "text", nullable: true },
      { name: "last_name", type: "text", nullable: true },
      { name: "short_name", type: "text", nullable: true },
      { name: "player_position", type: "text" },
      { name: "positions_json", type: "jsonb", default: jsonbArrayDefault },
      { name: "player_team", type: "text", nullable: true },
      { name: "sportsdata_id", type: "text", nullable: true },
      { name: "fetched_at", type: "timestamptz" },
      createdAtColumn,
    ],
    primaryKey: ["player_id"],
    indexes: [
      { name: "fantasy_pros_players_position_idx", columns: ["player_position"] },
    ],
  },
  {
    name: "fantasy_pros_fetch_log",
    columns: [
      { name: "dataset", type: "text" },
      { name: "last_fetched_at", type: "timestamptz" },
      { name: "last_succeeded_at", type: "timestamptz", nullable: true },
      { name: "request_count", type: "bigint", default: "0" },
      { name: "row_count", type: "integer", default: "0" },
      { name: "last_error", type: "text", nullable: true },
      createdAtColumn,
      updatedAtColumn,
    ],
    primaryKey: ["dataset"],
  },
];
