import type { PlayerNewsFeed } from "./playerNewsSchema";

export const playerNewsFeedFixture: PlayerNewsFeed = {
  generatedAt: "2026-08-16T14:00:00.000Z",
  sourceMode: "all",
  summary: {
    fadeCount: 0,
    filteredCount: 2,
    moveUpCount: 1,
    noChangeCount: 0,
    totalCount: 2,
    watchCount: 1,
  },
  providers: [{
    detail: "Recent NFL headlines",
    key: "rotowire-rss",
    label: "RotoWire RSS",
    status: "available",
  }],
  items: [{
    auction: { recommendedMaxBid: 22, status: "available", tags: ["target"] },
    availability: { detail: "$18 live / $22 max", status: "available" },
    category: "Role",
    draftAction: "Move up",
    fantasyImpact: "The larger role improves his weekly ceiling.",
    fetchedAt: "2026-08-16T13:55:00.000Z",
    headline: "Ladd McConkey: Expected to lead the passing game.",
    id: "rotowire-ladd",
    impactScore: 1,
    normalizedPlayerName: "ladd mcconkey",
    player: "Ladd McConkey",
    position: "WR",
    providerItemId: "ladd-1",
    source: { provider: "RotoWire RSS", quality: "unreviewed", url: "https://example.com/ladd" },
    sourceDate: "2026-08-16T13:30:00.000Z",
    teamAbbreviation: "LAC",
  }, {
    auction: { status: "keeper", tags: [] },
    availability: { detail: "Short King keeper at $50", status: "keeper" },
    category: "Practice",
    draftAction: "Watch",
    fantasyImpact: "Monitor his participation before draft day.",
    headline: "De'Von Achane was limited in practice.",
    id: "local-achane",
    impactScore: -0.5,
    normalizedPlayerName: "devon achane",
    player: "De'Von Achane",
    position: "RB",
    providerItemId: "local-1",
    source: { provider: "Our evidence" },
    teamAbbreviation: "MIA",
  }],
};
