import { auctionMockResponseSchema } from "../api/mockDraftSchemas.js";

export const auctionMockResponseFixture = () => auctionMockResponseSchema.parse({
  mockSession: {
    draftMode: { format: "auction" },
    id: "mock-1",
    revision: 3,
    seasonId: "season-1",
    status: "active",
    teamId: "team-cam",
  },
  state: {
    auctionEvents: [
      {
        nominationNumber: 1,
        playerId: "gibbs",
        playerName: "Jahmyr Gibbs",
        price: 70,
        sequence: 1,
        teamId: "team-seth",
        teamName: "Sentinels",
        text: "Sentinels opened at $70",
        type: "nomination",
      },
      {
        nominationNumber: 1,
        playerId: "gibbs",
        playerName: "Jahmyr Gibbs",
        price: 71,
        sequence: 2,
        teamId: "team-beaton",
        teamName: "Dart Vader",
        text: "Dart Vader bid $71",
        type: "bid",
      },
    ],
    board: {
      players: [
        {
          available: true,
          byeWeek: 6,
          expectedPrice: 76,
          humanValue: 81,
          id: "gibbs",
          name: "Jahmyr Gibbs",
          position: "RB",
          status: "nominated",
          teamAbbreviation: "DET",
          week1Projection: 20.1,
        },
        {
          available: true,
          byeWeek: 11,
          expectedPrice: 70,
          humanValue: 75,
          id: "puka",
          name: "Puka Nacua",
          position: "WR",
          status: "available",
          teamAbbreviation: "LAR",
          week1Projection: 17.6,
        },
      ],
    },
    configuration: {
      budgetDollars: 200,
      humanTeamId: "team-cam",
      minimumBidDollars: 1,
      positionMaximums: { DST: 1, K: 1, QB: 1, RB: 3, TE: 1, WR: 3 },
    },
    sales: [],
    session: {
      canComplete: false,
      canUndo: true,
      currentNomination: {
        currentPrice: 71,
        expectedPrice: 76,
        highestBidderTeamId: "team-beaton",
        highestBidderTeamName: "Dart Vader",
        humanCanBuy: true,
        humanCanPass: true,
        humanPassed: false,
        nextBid: 72,
        nominatedByTeamId: "team-seth",
        nominatedByTeamName: "Sentinels",
        number: 1,
        playerId: "gibbs",
        playerName: "Jahmyr Gibbs",
        position: "RB",
      },
      humanTeamId: "team-cam",
      id: "mock-1",
      nominationsCompleted: 0,
      phase: "awaiting_human_bid",
      revision: 3,
      status: "active",
    },
    teams: [
      {
        budgetDollars: 200,
        budgetRemaining: 150,
        id: "team-cam",
        isHuman: true,
        maxBid: 136,
        name: "Short King",
        positionCounts: { RB: 1 },
        roster: [{
          expectedPrice: 50,
          playerId: "achane",
          playerName: "De'Von Achane",
          position: "RB",
          price: 50,
          rosterSlot: "RB1",
          source: "keeper",
        }],
        rosterSlotsRemaining: 15,
        slots: [
          { eligiblePositions: ["RB"], playerId: "achane", slot: "RB1" },
          { eligiblePositions: ["RB"], slot: "RB2" },
          { eligiblePositions: ["RB", "WR", "TE"], slot: "FLEX" },
        ],
        spent: 50,
      },
      {
        budgetDollars: 200,
        budgetRemaining: 200,
        id: "team-beaton",
        isHuman: false,
        maxBid: 198,
        name: "Dart Vader",
        positionCounts: {},
        roster: [],
        rosterSlotsRemaining: 3,
        slots: [
          { eligiblePositions: ["RB"], slot: "RB1" },
          { eligiblePositions: ["WR"], slot: "WR1" },
          { eligiblePositions: ["RB", "WR", "TE"], slot: "FLEX" },
        ],
        spent: 0,
      },
    ],
  },
});
